import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavegadorDerecha from "@/components/NavegadorDerecha";
import NavegadorAbajo from "@/components/NavegadorAbajo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Posts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <NavegadorDerecha />
            {children}
        </div>
        <NavegadorAbajo />
      </body>
    </html>
  );
}
